{"name": "test_put_invalid_data_status_code[request_data2]", "status": "passed", "description": "\n        Проверка статуса ответа метода PUT при запросе с невалидными данными.\n        Ожидаемый результат 400\n        ", "attachments": [{"name": "log", "source": "14f2d175-02d2-4da6-b70b-ff0169692176-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "request_data", "value": "{'key': 'wrong', 'value': 'wrong', 'NEW': 'new'}"}], "start": 1591447258628, "stop": 1591447258635, "uuid": "c91267f6-d0d2-45ae-b135-2b29b8965f85", "historyId": "17324b298c6999a698c98368596ae55e", "testCaseId": "4234cd3052612d52fa8b63503de09fec", "fullName": "tests.test_api_put.TestPut#test_put_invalid_data_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_put"}, {"name": "subSuite", "value": "TestPut"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "5837-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_put"}]}