{"name": "test_put_invalid_data_status_code[request_data0]", "status": "passed", "description": "\n        Проверка статуса ответа метода PUT при запросе с невалидными данными.\n        Ожидаемый результат 400\n        ", "attachments": [{"name": "log", "source": "7b957995-bea0-4496-ae7b-1c8940b94a91-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "request_data", "value": "{'value': 'wrong'}"}], "start": 1591447258591, "stop": 1591447258597, "uuid": "0ee673a3-1d98-4ab3-a942-35964abfc10e", "historyId": "cb46ce2c3e7eea9229172a2279e67847", "testCaseId": "4234cd3052612d52fa8b63503de09fec", "fullName": "tests.test_api_put.TestPut#test_put_invalid_data_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_put"}, {"name": "subSuite", "value": "TestPut"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "5837-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_put"}]}